name: This is a deployment workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  deploy:
    name: This is a deployment job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ember
    steps:
      - name: Run some commands
        run: echo "This is a test"
