name: This is a deployment workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  deploy:
    name: This is a deployment job
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@percy'))
    steps:
      - name: Run some commands
        run: echo "This is a test"
