name: This is a deployment workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
  issue_comment:
    types: [created]
jobs:
  deploy:
    name: This is a deployment job
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@deploy run')
    steps:
      - name: Run some commands
        run: echo "This is a test"
