name: This is a deployment workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  deploy:
    name: This is a deployment job
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@deploy run'))
    steps:
      - name: Add 👍 Reaction to Comment
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: '+1'
            })

      - name: Comment on the Issue or PR
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "🚀 Deployment has started!"
            })

      - name: Run some commands
        run: echo "This is a test"
