name: Test PR Comments

on:
  issue_comment:
    types: [created]

permissions:
  issues: read
  pull-requests: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR Comment Event
        run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Is it a PR?: ${{ github.event.issue.pull_request != null }}"
